### ISSUE TITLE
Doesn't work for polygons

### ISSUE THREAD

**Issue by ungoldman** [morganherlocker/geojson2csv#1]
I can't convert a GeoJSON file with polygon data to CSV!

e.g. https://gist.github.com/ngoldman/05603d639276b0c1f69d

Long story short it ends up producing some very invalid CSV data:

```
lat,lon
43.2421875,56.17002298293205,55.54687499999999,46.07323062540838,86.484375,56.559482483762245,61.17187499999999,63.074865690586634,48.8671875,61.438767493682825,43.2421875,56.17002298293205,undefined
```

I stumbled onto this while trying to figure out what the standard notation for a polygon is in CSV. So far the only reliable one I've found is WKT which is a little gross. Thoughts?

**Comment by morganherlocker** [comment]
@ngoldman yeah, no great options here, much less a standard. I would probably have a geometry column populated by the geojson geometry object stringified. Not useful as an interop format, but I would guess it would reliably capture the data.

**Comment by ungoldman** [comment]
:ship: :wave:
